version: '3'
services:
  db:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password

    environment:

      MYSQL_DATABASE: laterraza
      MYSQL_ROOT_PASSWORD: root
    
    ports:
      - 3306:3306

    volumes:
      - ./db:/var/lib/mysql